kind: pipeline
type: docker
name: Build Master

steps:

- name: docker build
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: 
      from_secret: docker_reponame
    tags: latest

trigger:
  branch:
  - master

---
kind: pipeline
type: docker
name: Build Tags

steps:

- name: docker build
  image: plugins/docker
  settings:
    auto_tag: true
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: 
      from_secret: docker_reponame
    tags: latest

trigger:
  event:
  - tag

---
kind: pipeline
type: docker
name: Build Dev

steps:

- name: docker build
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: 
      from_secret: docker_reponame
    tags: dev

trigger:
  branch:
    - frontend

---
kind: pipeline
type: docker
name: Build Demo

steps:

- name: docker build
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: 
      from_secret: docker_reponame
    dockerfile: Demo.Dockerfile
    tags: demo

trigger:
  branch:
  - master

---
kind: pipeline
type: docker
name: Notify

steps:

- name: notify
  image: plugins/matrix
  settings:
    homeserver: https://matrix.zble.sk
    roomid: 
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
  
depends_on:
- Build Dev
- Build Master
- Build Tags
- Build Demo
