kind: pipeline
type: docker
name: default

steps:
- name: node
  image: node:8
  commands:
  - cd Obskurnee
  - cd ClientApp
  - npm install
  - npm run build -- --prod

- name: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
  - dotnet publish -c ReleaseNoNode -o published
  when:
    branch: master

- name: seeFiles
  image: alpine
  commands:
  - echo $PWD
  - cd Obskurnee
  - ls -R
